spring:
  application:
    name: dbank-operation-service
  jpa:
    hibernate:
      ddl-auto: none
    #    properties:
    #      hibernate:
    #        dialect: org.hibernate.dialect.PostgreSQLDialect
    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml
  datasource:
    url: jdbc:postgresql://${DB_HOST}/db_cities_cont
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

springdoc:
  swagger-ui:
    enabled: true
    path: /public/swagger-ui
    config-url: /public/openapi/swagger-config
    url: /public/openapi
    disable-swagger-default-url: true
  api-docs:
    path: /public/openapi

server:
  port: 8080